# Generated by Django 3.2.2 on 2021-07-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloudiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='общая облачность')),
                ('scale', models.IntegerField(blank=True, null=True, verbose_name='градация')),
            ],
            options={
                'verbose_name': 'общая облачность',
                'verbose_name_plural': 'общая облачность',
                'db_table': 'cloudiness',
            },
        ),
        migrations.CreateModel(
            name='CloudinessCl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='общая облачность')),
                ('scale', models.IntegerField(blank=True, null=True, verbose_name='градация')),
            ],
            options={
                'verbose_name': 'процент наблюдающихся облаков',
                'verbose_name_plural': 'процент наблюдающихся облаков',
                'db_table': 'cloudiness_cl',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='место')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'название места',
                'verbose_name_plural': 'названия мест',
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='WindDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='направление ветра (румбы) на высоте 10 - 12 м над земной поверхностью, осреднённое за 10-минутный период, непосредственно предшествующий сроку наблюдения')),
            ],
            options={
                'verbose_name': 'направление ветра',
                'verbose_name_plural': 'направления ветра',
                'db_table': 'wind_directions',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='идентификатор')),
                ('latitude', models.FloatField(verbose_name='широта метеорологической станции')),
                ('longitude', models.FloatField(verbose_name='долгота метеорологической станции')),
                ('rp5_link', models.CharField(max_length=255, verbose_name='ссылка на метеостанцию, rp5')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='дата последней загрузки')),
                ('data_type', models.CharField(max_length=50, verbose_name='метеостанция, METAR, метеодатчик')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='страна')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.place', verbose_name='место')),
            ],
            options={
                'verbose_name': 'метеостанция',
                'verbose_name_plural': 'метеостанции',
                'db_table': 'weather_stations',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'регионы',
                'db_table': 'regions',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='регион'),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='температура воздуха, (°С) на высоте 2 м над поверхностью земли')),
                ('pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='атмосферное давление на уровне станции (миллиметры ртутного столба)')),
                ('pressure_converted', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='атмосферное давление, приведённое к среднему уровню моря (миллиметры ртутного столба)')),
                ('baric_trend', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='барическая тенденция: изменение атмосферного давления за последние 3 часа (миллиметры ртутного столба)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='относительная влажность (%) на высоте 2 м над поверхностью земли')),
                ('wind_speed', models.IntegerField(blank=True, null=True, verbose_name='скорость ветра на высоте 10-12 м над земной поверхностью, осреднённая за 10-минутный период, непосредственно предшествующий сроку наблюдения (метры в секунду)')),
                ('max_wind_speed', models.IntegerField(blank=True, null=True, verbose_name='максимальное значение порыва ветра на высоте 10-12 метров над земной поверхностью за 10-минутный период, непосредственно предшествующий сроку наблюдения (метры в секунду)')),
                ('max_wind_speed_between', models.IntegerField(blank=True, null=True, verbose_name='максимальное значение порыва ветра на высоте 10-12 метров над земной поверхностью за период между сроками (метры в секунду)')),
                ('current_weather', models.TextField(blank=True, null=True, verbose_name='текущая погода, сообщаемая с метеорологической станции')),
                ('past_weather', models.CharField(blank=True, max_length=255, null=True, verbose_name='прошедшая погода между сроками наблюдения 1')),
                ('past_weather_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='прошедшая погода между сроками наблюдения 2')),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='минимальная температура воздуха (°С) за прошедший период (не более 12 часов)')),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='максимальная температура воздуха (°С) за прошедший период (не более 12 часов)')),
                ('cloud_cl', models.CharField(blank=True, max_length=255, null=True, verbose_name='слоисто-кучевые, слоистые, кучевые и кучево-дождевые облака (Cl)')),
                ('cloud_hight', models.CharField(blank=True, max_length=255, null=True, verbose_name='высота основания самых низких облаков (м)')),
                ('cloud_cm', models.CharField(blank=True, max_length=255, null=True, verbose_name='высококучевые, высокослоистые и слоисто-дождевые облака (Cm)')),
                ('cloud_three', models.CharField(blank=True, max_length=255, null=True, verbose_name='перистые, перисто-кучевые и перисто-слоистые облака')),
                ('visibility', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='горизонтальная дальность видимости (км)')),
                ('dew_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='температура точки росы на высоте 2 метра над поверхностью земли (°С)')),
                ('rainfall', models.CharField(blank=True, max_length=50, null=True, verbose_name='количество выпавших осадков (мм)')),
                ('rainfall_time', models.IntegerField(blank=True, null=True, verbose_name='период времени за который накоплено указанное количество осадков (часы)')),
                ('soil_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='состояние поверхности почвы без снега или измеримого ледяного покрова')),
                ('soil_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='минимальная температура поверхности почвы за ночь (°С)')),
                ('soil_with_snow', models.CharField(blank=True, max_length=255, null=True, verbose_name='состояние поверхности почвы со снегом или измеримым ледяным покровом')),
                ('snow_hight', models.CharField(blank=True, max_length=255, null=True, verbose_name='высота снежного покрова (см)')),
                ('cloud_count', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cloudinesscl', verbose_name='количество всех наблюдающихся облаков Cl или, при отсутствии облаков Cl, количество всех наблюдающихся облаков Cm')),
                ('cloud_cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cloudiness', verbose_name='общая облачность (%)')),
                ('weather_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weatherstation', verbose_name='метеостанция')),
                ('wind_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.winddirection', verbose_name='направление ветра (румбы) на высоте 10 - 12 м над земной поверхностью, осреднённое за 10-минутный период, непосредственно предшествующий сроку наблюдения')),
            ],
            options={
                'verbose_name': 'погода',
                'verbose_name_plural': 'погода',
                'db_table': 'weather',
                'unique_together': {('weather_station', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('country', 'region', 'name')},
        ),
    ]
