# Generated by Django 3.2.2 on 2021-07-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudiness',
            name='description',
            field=models.CharField(max_length=150, unique=True, verbose_name='общая облачность'),
        ),
    ]
