# Generated by Django 3.2.2 on 2021-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cloudiness_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudiness',
            name='description',
            field=models.CharField(max_length=300, unique=True, verbose_name='общая облачность'),
        ),
    ]
