# Generated by Django 3.2.2 on 2021-07-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cloudiness_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=70, verbose_name='место'),
        ),
    ]
