# Generated by Django 3.2.2 on 2021-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudiness',
            name='description',
            field=models.CharField(max_length=350, unique=True, verbose_name='общая облачность'),
        ),
    ]
