# Generated by Django 4.0 on 2022-01-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_weatherstation_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='метеостанция, METAR, метеодатчик')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='latitude',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='longitude',
            field=models.FloatField(verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.weatherstationtype', verbose_name='тип'),
        ),
    ]
