# Generated by Django 4.0 on 2022-01-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_weatherstationtype_remove_weatherstation_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(verbose_name='долгота'),
        ),
    ]
