# Generated by Django 4.0 on 2022-01-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_weatherstation_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherstationtype',
            options={'verbose_name': 'тип метеостанции', 'verbose_name_plural': 'типы метеостанций'},
        ),
        migrations.AlterModelTable(
            name='weatherstationtype',
            table='weather_station_type',
        ),
    ]
