# Generated by Django 4.0 on 2022-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_weatherstationtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstationtype',
            name='type',
            field=models.CharField(max_length=50, unique=True, verbose_name='метеостанция, METAR, метеодатчик'),
        ),
    ]
