# Generated by Django 4.2.30 on 2026-07-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_weatherstationtype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinTemperatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата и время')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='минимальная температура воздуха, (°С) на высоте 2 м над поверхностью земли за весь период наблюдений')),
            ],
            options={
                'verbose_name': 'Минимальные температуры по станциям и даты когда эти температуры были зафиксированы',
                'db_table': 'min_temperatures',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'местоположение', 'verbose_name_plural': 'местоположения'},
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=70, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.place', verbose_name='место'),
        ),
    ]
